services:
  api:
    build:
      context: ./api
    ports:
      - "1323:1323"
    environment:
      UPLOAD_DIRECTORY: /var/lib/documind/uploads
    volumes:
      - document_uploads:/var/lib/documind/uploads

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  document_uploads: