// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: extractor.proto

package extractorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextExtractor_Extract_FullMethodName = "/extractor.TextExtractor/Extract"
)

// TextExtractorClient is the client API for TextExtractor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextExtractorClient interface {
	Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
}

type textExtractorClient struct {
	cc grpc.ClientConnInterface
}

func NewTextExtractorClient(cc grpc.ClientConnInterface) TextExtractorClient {
	return &textExtractorClient{cc}
}

func (c *textExtractorClient) Extract(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, TextExtractor_Extract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextExtractorServer is the server API for TextExtractor service.
// All implementations must embed UnimplementedTextExtractorServer
// for forward compatibility.
type TextExtractorServer interface {
	Extract(context.Context, *ExtractRequest) (*ExtractResponse, error)
	mustEmbedUnimplementedTextExtractorServer()
}

// UnimplementedTextExtractorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextExtractorServer struct{}

func (UnimplementedTextExtractorServer) Extract(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Extract not implemented")
}
func (UnimplementedTextExtractorServer) mustEmbedUnimplementedTextExtractorServer() {}
func (UnimplementedTextExtractorServer) testEmbeddedByValue()                       {}

// UnsafeTextExtractorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextExtractorServer will
// result in compilation errors.
type UnsafeTextExtractorServer interface {
	mustEmbedUnimplementedTextExtractorServer()
}

func RegisterTextExtractorServer(s grpc.ServiceRegistrar, srv TextExtractorServer) {
	// If the following call pancis, it indicates UnimplementedTextExtractorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextExtractor_ServiceDesc, srv)
}

func _TextExtractor_Extract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextExtractorServer).Extract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextExtractor_Extract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextExtractorServer).Extract(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextExtractor_ServiceDesc is the grpc.ServiceDesc for TextExtractor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextExtractor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "extractor.TextExtractor",
	HandlerType: (*TextExtractorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Extract",
			Handler:    _TextExtractor_Extract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extractor.proto",
}
