// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/extractor.proto

package extractorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DocumentProcessorClient is the client API for DocumentProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentProcessorClient interface {
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (DocumentProcessor_ProcessClient, error)
	EmbedQuestion(ctx context.Context, in *EmbedQuestionRequest, opts ...grpc.CallOption) (*EmbedQuestionResponse, error)
	AnswerQuestion(ctx context.Context, in *AnswerQuestionRequest, opts ...grpc.CallOption) (DocumentProcessor_AnswerQuestionClient, error)
}

type documentProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentProcessorClient(cc grpc.ClientConnInterface) DocumentProcessorClient {
	return &documentProcessorClient{cc}
}

func (c *documentProcessorClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (DocumentProcessor_ProcessClient, error) {
	stream, err := c.cc.NewStream(ctx, &DocumentProcessor_ServiceDesc.Streams[0], "/extractor.DocumentProcessor/Process", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentProcessorProcessClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DocumentProcessor_ProcessClient interface {
	Recv() (*ProcessEvent, error)
	grpc.ClientStream
}

type documentProcessorProcessClient struct {
	grpc.ClientStream
}

func (x *documentProcessorProcessClient) Recv() (*ProcessEvent, error) {
	m := new(ProcessEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *documentProcessorClient) EmbedQuestion(ctx context.Context, in *EmbedQuestionRequest, opts ...grpc.CallOption) (*EmbedQuestionResponse, error) {
	out := new(EmbedQuestionResponse)
	err := c.cc.Invoke(ctx, "/extractor.DocumentProcessor/EmbedQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentProcessorClient) AnswerQuestion(ctx context.Context, in *AnswerQuestionRequest, opts ...grpc.CallOption) (DocumentProcessor_AnswerQuestionClient, error) {
	stream, err := c.cc.NewStream(ctx, &DocumentProcessor_ServiceDesc.Streams[1], "/extractor.DocumentProcessor/AnswerQuestion", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentProcessorAnswerQuestionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DocumentProcessor_AnswerQuestionClient interface {
	Recv() (*AnswerEvent, error)
	grpc.ClientStream
}

type documentProcessorAnswerQuestionClient struct {
	grpc.ClientStream
}

func (x *documentProcessorAnswerQuestionClient) Recv() (*AnswerEvent, error) {
	m := new(AnswerEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DocumentProcessorServer is the server API for DocumentProcessor service.
// All implementations must embed UnimplementedDocumentProcessorServer
// for forward compatibility
type DocumentProcessorServer interface {
	Process(*ProcessRequest, DocumentProcessor_ProcessServer) error
	EmbedQuestion(context.Context, *EmbedQuestionRequest) (*EmbedQuestionResponse, error)
	AnswerQuestion(*AnswerQuestionRequest, DocumentProcessor_AnswerQuestionServer) error
	mustEmbedUnimplementedDocumentProcessorServer()
}

// UnimplementedDocumentProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentProcessorServer struct {
}

func (UnimplementedDocumentProcessorServer) Process(*ProcessRequest, DocumentProcessor_ProcessServer) error {
	return status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedDocumentProcessorServer) EmbedQuestion(context.Context, *EmbedQuestionRequest) (*EmbedQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmbedQuestion not implemented")
}
func (UnimplementedDocumentProcessorServer) AnswerQuestion(*AnswerQuestionRequest, DocumentProcessor_AnswerQuestionServer) error {
	return status.Errorf(codes.Unimplemented, "method AnswerQuestion not implemented")
}
func (UnimplementedDocumentProcessorServer) mustEmbedUnimplementedDocumentProcessorServer() {}

// UnsafeDocumentProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentProcessorServer will
// result in compilation errors.
type UnsafeDocumentProcessorServer interface {
	mustEmbedUnimplementedDocumentProcessorServer()
}

func RegisterDocumentProcessorServer(s grpc.ServiceRegistrar, srv DocumentProcessorServer) {
	s.RegisterService(&DocumentProcessor_ServiceDesc, srv)
}

func _DocumentProcessor_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentProcessorServer).Process(m, &documentProcessorProcessServer{stream})
}

type DocumentProcessor_ProcessServer interface {
	Send(*ProcessEvent) error
	grpc.ServerStream
}

type documentProcessorProcessServer struct {
	grpc.ServerStream
}

func (x *documentProcessorProcessServer) Send(m *ProcessEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _DocumentProcessor_EmbedQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentProcessorServer).EmbedQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extractor.DocumentProcessor/EmbedQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentProcessorServer).EmbedQuestion(ctx, req.(*EmbedQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentProcessor_AnswerQuestion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnswerQuestionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentProcessorServer).AnswerQuestion(m, &documentProcessorAnswerQuestionServer{stream})
}

type DocumentProcessor_AnswerQuestionServer interface {
	Send(*AnswerEvent) error
	grpc.ServerStream
}

type documentProcessorAnswerQuestionServer struct {
	grpc.ServerStream
}

func (x *documentProcessorAnswerQuestionServer) Send(m *AnswerEvent) error {
	return x.ServerStream.SendMsg(m)
}

// DocumentProcessor_ServiceDesc is the grpc.ServiceDesc for DocumentProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "extractor.DocumentProcessor",
	HandlerType: (*DocumentProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmbedQuestion",
			Handler:    _DocumentProcessor_EmbedQuestion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Process",
			Handler:       _DocumentProcessor_Process_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AnswerQuestion",
			Handler:       _DocumentProcessor_AnswerQuestion_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/extractor.proto",
}
